### ISSUE TITLE
Респонсив

### ISSUE THREAD

**Issue by a-poluhin** [NZMinusDev/TOXIN#1]
В хедере при ширине 1440px начинает наблюдаться проблема в выравнивание меню.

![image](https://user-images.githubusercontent.com/10168007/128853180-99047e43-af1c-412d-8ca8-96976ef8ed01.png)

В пагинации ломается верстка чутка  при смене страницы.

![image](https://user-images.githubusercontent.com/10168007/128854235-58c324fc-c2d4-485b-9af4-59b72de15e90.png)

На мобильной ширине и ширине 1440px
кругляшь у radio смещается от центра

![image](https://user-images.githubusercontent.com/10168007/128855830-522045bc-52bc-4084-a5fa-ee7745201972.png)

**Comment by NZMinusDev** [comment]
С кругляшом могу решить задав абсолютные размеры для окружности и круга (там проблема не в позиционировании, а в том, что браузер при отрисовке сбивается в расчетах относительных размеров), но мне хотелось бы как-нибудь оставить элемент отзывчивым как это и происходит у native элемента. Пока ищу подходящий способ.

**Comment by NZMinusDev** [comment]
Перепробовав кучу вариантов, остановился на решении с SVG.
