### ISSUE TITLE
js- префиксы

### ISSUE THREAD

**Issue by a-poluhin** [NZMinusDev/TOXIN#2]
По стандарту все выражения, которые используются для поиска по DOM, должны иметь префикс js-
Глянь у тебя в не которых местах еще остались=)

![image](https://user-images.githubusercontent.com/10168007/128856728-86d884a8-b424-403a-9270-8b962c1a54ff.png)

**Comment by NZMinusDev** [comment]
Эти классы относятся к внутренней структуре стороннего плагина, который изолирован и добавляет именно эти элементы динамически при подключении.

**Comment by a-poluhin** [comment]
Ага понял=) Тогда закрываю)
