### ISSUE TITLE
Разные мелочи

### ISSUE THREAD

**Issue by Geksanit** [NZMinusDev/TOXIN#23]
Опишу, разные мелочи просто тебе к сведению, исправлять не обязательно и можешь закрыть ишью.
1. .vscode лучше добавить в .gitignore, у всех свои настройки)
2. `app/src/` -> `src/`
![image](https://user-images.githubusercontent.com/31949379/149657258-c561e20d-1d98-4353-ab78-5269fd4fbdbc.png)
3. бэм элементы можно назвать проще, `.room-card__room-titl`e -> `.room-card__title` и т.д.
![image](https://user-images.githubusercontent.com/31949379/149657343-ea1e2670-9ba9-4888-a2b6-630727ba0554.png)
4. тут padding используется как margin.
5. многие блоки в названии имеют `form-`: `form-rate-button` и другие. Это не добавляет никакой семантики, не всегда кнопки находятся в форме.

**Comment by NZMinusDev** [comment]
1. Сейчас в workspace оставлены только настройки линтеров и части расширений используемых в проекте + набор специфичных для проекта сниппетов: разве это плохая практика расшаривать подобного рода конфигурации?

**Comment by Geksanit** [comment]
На практике так никто не делает. У всех могут быть разные IDE, расширения, настройки и сниппеты. А сниппетами, если нужно, обмениваются другими путями.
