### ISSUE TITLE
Наименования файлов и папок

### ISSUE THREAD

**Issue by a-poluhin** [NZMinusDev/TOXIN#3]
Ненужно файлы именовать по подобию БЭМ.
![image](https://user-images.githubusercontent.com/10168007/129908155-5bc552d6-60ff-40e7-b3e2-fac1b9120678.png)
Лучше просто navigation-item, navigation-list. Для файлов также вместо nav-bar__navigation-list.pug вот так navigation-list.pug а принадлежность элемента будет видно в древе файлов.

**Comment by NZMinusDev** [comment]
Это необходимо для сборщика: он подключает файлы технологий(css,scss,js,ts) путём анализа классов, присутствующих на страницах, и составления деклараций на основе которых происходит импорт всего необходимого. К тому же, в чем преимущество от подобного переименования?
