### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by OlgaMaurer** [NZMinusDev/TOXIN#5]
Если в файле содержится класс, то имя этого файла должно соответствовать имени класса, к примеру если у тебя имя класса NavBar, то и имя файла должно быть NavBar

**Comment by NZMinusDev** [comment]
В стандартах такого не встречал, а [airbnb](https://github.com/airbnb/javascript#naming--filename-matches-export) рекомендует это делать только для файлов с default экспортами(что как я понимаю улучшает development experience при использовании сниппетов), кроме того в этом проекте сборщик завязан на наименовании папок, в #3 объяснение.

**Comment by OlgaMaurer** [comment]
Хорошо, закрываю ишью
