### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by OlgaMaurer** [NZMinusDev/TOXIN#7]
Добавь пожалуйста к своему проекту [stylelint](https://stylelint.io/), [stylelint-prettier](https://github.com/prettier/stylelint-prettier) для форматирования стилей

**Comment by OlgaMaurer** [comment]
Пожалуйста настрой форматирование для файлов ts
![Inked2021-09-17-09-08-41_LI](https://user-images.githubusercontent.com/90188872/133735105-35506e71-4563-4168-aad5-375321f3d272.jpg)

**Comment by OlgaMaurer** [comment]
![2021-09-17-09-11-39](https://user-images.githubusercontent.com/90188872/133735363-96e7d1c6-ef29-4cb5-9786-3c4ecea66e89.png)

Длина строки в 80 символов считается одной из удобнейших для чтения, старайся не отходить далеко от этой цифры.
Такие варианты будут читабельнее

![2021-09-17-09-12-21](https://user-images.githubusercontent.com/90188872/133735400-b384bdd5-878d-4c16-bec8-a7b47784b2c9.png)

**Comment by NZMinusDev** [comment]
> ![2021-09-17-09-11-39](https://user-images.githubusercontent.com/90188872/133735363-96e7d1c6-ef29-4cb5-9786-3c4ecea66e89.png)
> 
> Длина строки в 80 символов считается одной из удобнейших для чтения, старайся не отходить далеко от этой цифры.
> Такие варианты будут читабельнее
> 
> ![2021-09-17-09-12-21](https://user-images.githubusercontent.com/90188872/133735400-b384bdd5-878d-4c16-bec8-a7b47784b2c9.png)

В проекте используется ограничение в 100 символов(исходя из того что рекомендуют обычно 80-120)

**Comment by NZMinusDev** [comment]
> Пожалуйста настрой форматирование для файлов ts
> ![Inked2021-09-17-09-08-41_LI](https://user-images.githubusercontent.com/90188872/133735105-35506e71-4563-4168-aad5-375321f3d272.jpg)

Имеются ввиду отступы между методами? - мне кажется это плохим решением, предпочитаю группировать методы по смыслу, что упрощает навигацию по документу и проще работать в рамках одного блока.

**Comment by NZMinusDev** [comment]
По обоим пунктам: если скажешь что все равно надо изменить - сделаю.

**Comment by OlgaMaurer** [comment]
> Имеются ввиду отступы между методами? - мне кажется это плохим решением, предпочитаю группировать методы по смыслу, что упрощает навигацию по документу и проще работать в рамках одного блока.

Да, я имела в виду отступы между методами. Форматирование кода должно быть единообразным. Группировать методы по смыслу можно просто располагая их друг за другом, от более важного к менее важному, при этом отсутствие отступов никак не влияет на их связывание

**Comment by OlgaMaurer** [comment]
> В проекте используется ограничение в 100 символов(исходя из того что рекомендуют обычно 80-120) - мне так удобнее из-за широкоформатного монитора.

Это конечно индивидуальные предпочтения, но обычно на проектах используют ограничение в 80 символов.
